
# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_test?characterEncoding=utf8&useSSL=false
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis的配置信息
  redis:
    port: 6379
    host: 114.132.221.156
    database: 2
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
  servlet:
    session:
      timeout: 1800

  #时间格式 只对Date生效
  jackson:
    date-format: yyy-MM-dd HH:mm
    time-zone: GMT+8
#mybatis 配置信息
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  configuration: # 配置打印 MyBatis 执行的 SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #自动驼峰转换
# 配置打印 MyBatis 执行的 SQL
logging:
  file:
    name: logs/springboot.log
  logback:
    rollingpolicy:
      max-file-size: 1KB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
  level:  #设置打印sql语句日志的级别
    com:
      example:
        demo: debug
