server:
  port: 9090

# ???????
demo:
  helo: asdf
  key1: hajdk,afw
  key2: jfka

# ????
student:
  id: 1
  name: zhangsan
  age: 23

# ????
dbtypes:
  name:
    - mysql
    - sqlserver
    - db2
  key:
    key1: key1
    key2: key2